name: Runs unit tests on PRs
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: npm install and test
        run: |
          npm install
          npm test
        env:
          CI: true
